name: Call a reusable workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-intellij:
    uses: bpmct/jetbrains-indexer/.github/workflows/build-and-push.yaml@main
    with:
      IDE: ideaIU
      IDE_SHORT: ideaIU
      IDE_CODE: idea
    secrets:
      token: ${{ secrets.GHCR_PAT }}
