name: Build and Push Images
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # define job to build and publish docker image
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

  build-intellij-idea:
    name: Build (InteliJ IDEA)
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./image
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/oskardudycz/eventsourcing.nodejs/simple:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
