name: Call a reusable workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-intellij:
    uses: bpmct/jetbrains-indexer/.github/workflows/build-and-push.yaml@master
    with:
      IDE: ideaIU
      IDE_SHORT: idea
      IDE_CODE: idea
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
  build-webstorm:
    uses: bpmct/jetbrains-indexer/.github/workflows/build-and-push.yaml@master
    with:
      IDE: WebStorm
      IDE_SHORT: webstorm
      IDE_CODE: webstorm
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
